os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.3"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=8.9.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - chmod +x mvnw
  - docker run -d --rm --name=ispn -p 11222:11222 -e "APP_USER=user" -e "APP_PASS=changeme" jboss/infinispan-server:9.1.4.Final -Djboss.default.jgroups.stack=tcp
  - ./mvnw clean test
  - docker stop ispn
  - yarn test
  - ./mvnw verify -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
