apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: equoid-data-handler-foo
    name: equoid-data-handler-foo
  spec:
    replicas: 1
    selector:
      app: equoid-data-handler-foo
      deploymentconfig: equoid-data-handler-foo
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: equoid-data-handler-foo
          deploymentconfig: equoid-data-handler-foo
      spec:
        containers:
        - image: docker-registry.default.svc:5000/255/equoid-data-handler-90:latest
          name: equoid-data-handler-90
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - equoid-data-handler-90
        from:
          kind: ImageStreamTag
          name: equoid-data-handler-90:latest
          namespace: "255"
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
