#
# Application template.
#
# This defines all the configurable parameters and other objects that are needed to run the jHipster application
# service. This template can even be saved in OpenShift namespace as well so that have the flexibility to do any project specific
# customizations. Pls note wherever displayName says *** PLEASE DO NOT CHANGE THIS ***, don't touch that as those parameters will be
# referenced in other places.
#
apiVersion: v1
kind: Template
metadata:
  name: equoid-app-template
  namespace: equoid
  annotations:
    description: This template defines objects that are required to spin up an equoid service pod
    tags: equoid, service
    openshift.io/display-name: equoid-template
    openshift.io/long-description: This template provides objects that are required to spin up a equoid service pod.
    openshift.io/provider-display-name: Equoid
labels:
  app: equoid-ui
  createdBy: radanalytics.io
parameters:
  -
    name: APPLICATION_NAME
    value: equoid
    description: Name of the application
    required: true
    displayName: Application Name
  -
    name: PUBLISHER_URL
    value: "equoid-data-publisher:8080"
    description: Publisher URL (host:port)
    required: true
    displayName: "Publisher service url in form host:port"
  -
    name: KEYCLOAK_URL
    value: "127.0.0.1:9080"
    description: Keycloak URL (host:port)
    required: true
    displayName: "Keycloak service url in form host:port"
  -
    name: APP_PORT
    value: "8080"
    description: Port of the application
    required: true
    displayName: Application Port
objects:
  -
    apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources:
      replicas: "1"
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
          - name: ${APPLICATION_NAME}
            image: jkremser/equoid:0.0.7
            imagePullPolicy: IfNotPresent
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,swagger
            - name: JHIPSTER_METRICS_LOGS_ENABLED
              value: "true"
            - name: JHIPSTER_METRICS_PROMETHEUS_ENABLED
              value: "true"
            - name: JHIPSTER_METRICS_PROMETHEUS_ENDPOINT
              value: "/prometheusMetrics"
            - name: KEYCLOAK_URL
              value: ${KEYCLOAK_URL}
            - name: PUBLISHER_URL
              value: ${PUBLISHER_URL}
            - name: INFINISPAN_SERVICE_HOST
              value: datagrid-hotrod
            - name: INFINISPAN_SERVICE_PORT
              value: "11222"
            ports:
            - name: http
              containerPort: "${APP_PORT}"
            - name: debug
              containerPort: 5005
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 15
              timeoutSeconds: 1
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
      annotations:
        service.alpha.openshift.io/dependencies: '[{"name":"keycloak", "namespace": "", "kind": "Service"}]'
    spec:
      selector:
        app: ${APPLICATION_NAME}
      type: LoadBalancer
      ports:
      - name: http
        port: "${APP_PORT}"
      - name: debug
        port: 5005
  -
    apiVersion: v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}
    spec:
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: "100"
      port:
        targetPort: "http"
      wildcardPolicy: None
